const products = [
    {
        title: "Stylish and Versatile Men's Casual Shirt for Everyday Comfort",
        name: "Shirt",
        imgURL: "https://images.pexels.com/photos/731909/pexels-photo-731909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 50.99,
        salePrice: 35.99,
        category: "Clothing",
        rating: 4.5,
        description: "This casual shirt is crafted from premium cotton fabric, making it breathable and lightweight. Designed for versatility, it can be worn for casual outings or semi-formal events. With a modern fit and durable stitching, it ensures long-lasting comfort and style. Pair it with jeans or chinos for a complete look.",
    },
    {
        title: "Elegant and Spacious Women's Handbag for All Occasions",
        name: "Bag",
        imgURL: "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 60.99,
        salePrice: 45.99,
        category: "Accessories",
        rating: 4.8,
        description: "This elegant handbag is a must-have accessory for every modern woman. Made from high-quality faux leather, it combines durability with style. It features multiple compartments to keep your essentials organized, including space for your phone, wallet, and makeup. Perfect for daily use or special occasions, this handbag complements any outfit effortlessly.",
    },
    {
        title: "Premium Noise-Canceling Wireless Headphones for Immersive Sound",
        name: "Headphones",
        imgURL: "https://images.pexels.com/photos/3394658/pexels-photo-3394658.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 120.99,
        salePrice: 89.99,
        category: "Electronics",
        rating: 4.6,
        description: "Experience superior sound quality with these wireless headphones. Equipped with advanced noise-canceling technology, they block out background noise, ensuring an immersive listening experience. The ergonomic design ensures a comfortable fit, even during extended use. With a long battery life and quick-charging feature, these headphones are perfect for music lovers and professionals alike.",
    },
    {
        title: "Comfortable and Durable Running Shoes for Fitness Enthusiasts",
        name: "Shoes",
        imgURL: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 80.99,
        salePrice: 59.99,
        category: "Footwear",
        rating: 4.7,
        description: "Step up your fitness game with these lightweight and durable running shoes. Engineered for optimal performance, they feature a breathable mesh upper that keeps your feet cool and dry. The cushioned sole provides excellent shock absorption, reducing stress on your joints during workouts. Suitable for both beginners and seasoned runners.",
    },
    {
        title: "Advanced Smartwatch with Health Monitoring and Customizable Design",
        name: "Watch",
        imgURL: "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 150.99,
        salePrice: 129.99,
        category: "Electronics",
        rating: 4.9,
        description: "Stay connected and track your fitness goals with this stylish smartwatch. Featuring a sleek design and customizable watch faces, it seamlessly blends technology with fashion. The smartwatch includes health monitoring features such as heart rate tracking, sleep analysis, and step counting. With its water-resistant build and long battery life, it's perfect for active lifestyles.",
    },
    {
        title: "Sleek and Modern Laptop Sleeve for Protection and Style",
        name: "Laptop Sleeve",
        imgURL: "https://images.pexels.com/photos/210241/pexels-photo-210241.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 25.99,
        salePrice: 19.99,
        category: "Accessories",
        rating: 4.4,
        description: "Protect your laptop in style with this sleek and modern laptop sleeve. Made with durable, water-resistant material, it shields your device from scratches and bumps. The slim design allows you to easily carry it in your bag or backpack, offering both convenience and protection. Available in multiple colors to match your personal style.",
    },
    {
        title: "Luxury Stainless Steel Men's Wristwatch for Timeless Elegance",
        name: "Wristwatch",
        imgURL: "https://images.pexels.com/photos/1109397/pexels-photo-1109397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 250.99,
        salePrice: 199.99,
        category: "Accessories",
        rating: 4.8,
        description: "This luxury wristwatch combines elegance with precision. Crafted from stainless steel with a polished finish, it features a sleek, minimalist design. The watch is water-resistant, durable, and designed to last. Perfect for formal occasions or daily wear, it's a timeless piece that enhances any outfit.",
    },
    {
        title: "Versatile and Comfortable Yoga Mat for Home or Studio Practice",
        name: "Yoga Mat",
        imgURL: "https://images.pexels.com/photos/1459399/pexels-photo-1459399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 30.99,
        salePrice: 22.99,
        category: "Sports & Fitness",
        rating: 4.7,
        description: "This high-quality yoga mat offers a comfortable, non-slip surface for your yoga practice. Made from eco-friendly materials, it provides excellent cushioning and support during your sessions. Lightweight and portable, it’s perfect for use at home or the studio. Available in a variety of colors to match your personal style.",
    },
    {
        title: "Premium Scented Candles for a Relaxing Ambience",
        name: "Candles",
        imgURL: "https://images.pexels.com/photos/1052190/pexels-photo-1052190.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 15.99,
        salePrice: 12.99,
        category: "Home Decor",
        rating: 4.5,
        description: "Transform your space with the calming scent of premium candles. Available in a variety of fragrances, these candles are made from natural wax and burn cleanly. The elegant glass jar adds a decorative touch to any room. Perfect for relaxation, meditation, or creating a cozy atmosphere in your home.",
    },
    {
        title: "High-Performance Bluetooth Speaker for Crystal Clear Sound",
        name: "Speaker",
        imgURL: "https://images.pexels.com/photos/3829441/pexels-photo-3829441.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 99.99,
        salePrice: 74.99,
        category: "Electronics",
        rating: 4.7,
        description: "Enjoy superior sound quality wherever you go with this high-performance Bluetooth speaker. Compact yet powerful, it delivers deep bass and crisp treble. The wireless design makes it perfect for outdoor activities, while the long-lasting battery ensures hours of uninterrupted music. Water-resistant and shockproof, it's ideal for any adventure.",
    },
    {
        title: "Cozy and Stylish Knit Sweater for Cold Weather",
        name: "Sweater",
        imgURL: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=800",
        previousPrice: 40.99,
        salePrice: 29.99,
        category: "Clothing",
        rating: 4.6,
        description: "Stay warm and stylish with this cozy knit sweater. Made from soft, breathable fabric, it provides ultimate comfort during cold weather. The classic design features a relaxed fit with ribbed cuffs and hem, making it easy to layer over your favorite shirts or jackets. Available in various colors to suit your style.",
    },
    {
        title: "Multi-Function Blender for Effortless Meal Preparation",
        name: "Blender",
        imgURL: "https://images.pexels.com/photos/3184187/pexels-photo-3184187.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 99.99,
        salePrice: 79.99,
        category: "Home Appliances",
        rating: 4.4,
        description: "This multi-function blender makes meal preparation quick and easy. Whether you're making smoothies, soups, or sauces, this powerful blender handles it all. The sleek design fits perfectly in any kitchen, and the easy-to-clean features make it a convenient tool for daily use. With adjustable speed settings and durable blades, it ensures smooth and consistent results every time.",
    },
    {
        title: "Classic and Comfortable Denim Jacket for All Seasons",
        name: "Jacket",
        imgURL: "https://images.pexels.com/photos/2387722/pexels-photo-2387722.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 70.99,
        salePrice: 49.99,
        category: "Clothing",
        rating: 4.6,
        description: "This classic denim jacket offers both style and comfort for all seasons. Made from durable, high-quality denim, it features a timeless design with button-down closures and front pockets. Whether you're layering it for warmth or wearing it as a statement piece, this versatile jacket pairs well with almost any outfit.",
    },
    {
        title: "Portable Travel Pillow for Neck Support and Comfort",
        name: "Travel Pillow",
        imgURL: "https://images.pexels.com/photos/326240/pexels-photo-326240.jpeg?auto=compress&cs=tinysrgb&w=800",
        previousPrice: 22.99,
        salePrice: 16.99,
        category: "Travel Accessories",
        rating: 4.5,
        description: "This portable travel pillow is designed to provide superior neck support during long journeys. The ergonomic shape helps prevent neck strain, allowing you to rest comfortably while traveling. Lightweight and compact, it's easy to pack and carry. The soft fabric ensures a pleasant experience on planes, trains, or road trips.",
    },
    {
        title: "Stylish and Functional Backpack for Daily Use",
        name: "Backpack",
        imgURL: "https://images.pexels.com/photos/1026279/pexels-photo-1026279.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 55.99,
        salePrice: 39.99,
        category: "Accessories",
        rating: 4.7,
        description: "This stylish backpack is perfect for students, professionals, or travelers. With multiple compartments, it helps keep your belongings organized while providing easy access. The padded shoulder straps and back panel offer comfort, even when carrying heavy loads. Whether you're commuting to work or exploring a new city, this backpack is your ideal companion.",
    },
    {
        title: "Elegant Rose Gold Bracelet with Gemstones",
        name: "Rose Gold Bracelet",
        imgURL: "https://images.pexels.com/photos/3663627/pexels-photo-3663627.jpeg",
        previousPrice: 120.99,
        salePrice: 99.99,
        category: "Jewelry",
        rating: 4.8,
        description: "A stunning rose gold bracelet adorned with beautiful gemstones. Perfect for adding a touch of elegance to your everyday look or special occasions.",
    },
    {
        title: "Luxurious Sapphire Pendant Necklace",
        name: "Sapphire Necklace",
        imgURL: "https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 250.00,
        salePrice: 220.00,
        category: "Jewelry",
        rating: 4.9,
        description: "A luxurious pendant featuring a dazzling sapphire stone. Set in sterling silver, this necklace is a perfect gift for special occasions or a personal treat.",
    },
    {
        title: "Adjustable Dog Harness for Comfort and Safety",
        name: "Dog Harness",
        imgURL: "https://images.pexels.com/photos/2320136/pexels-photo-2320136.jpeg",
        previousPrice: 40.00,
        salePrice: 29.99,
        category: "Pet Supplies",
        rating: 4.7,
        description: "Ensure your pet's safety and comfort with this adjustable dog harness. Made from durable material, it is ideal for long walks and outdoor adventures.",
    },
    {
        title: "Durable Pet Bed for Ultimate Comfort",
        name: "Pet Bed",
        imgURL: "https://images.pexels.com/photos/3156901/pexels-photo-3156901.jpeg",
        previousPrice: 50.00,
        salePrice: 39.99,
        category: "Pet Supplies",
        rating: 4.6,
        description: "A plush pet bed designed to offer your furry friend the ultimate comfort. It’s soft, cozy, and perfect for pets to rest after a long day of play.",
    },
    {
        title: "Car Dashboard Camera for Enhanced Safety",
        name: "Dashboard Camera",
        imgURL: "https://images.pexels.com/photos/3030377/pexels-photo-3030377.jpeg",
        previousPrice: 150.00,
        salePrice: 129.99,
        category: "Automotive",
        rating: 4.8,
        description: "This high-definition car dashboard camera records in 1080p, providing crystal-clear footage. Perfect for enhancing your driving safety and documenting road trips.",
    },
    {
        title: "Wireless Car Charger with Fast Charging Technology",
        name: "Car Charger",
        imgURL: "https://images.pexels.com/photos/1250743/pexels-photo-1250743.jpeg",
        previousPrice: 40.00,
        salePrice: 29.99,
        category: "Automotive",
        rating: 4.7,
        description: "Charge your phone quickly and wirelessly with this car charger. It’s designed to fit into your car's dashboard, offering fast charging without the hassle of cords.",
    },
    {
        title: "Modern Recliner Chair for Living Room Comfort",
        name: "Recliner Chair",
        imgURL: "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 300.00,
        salePrice: 249.99,
        category: "Furniture",
        rating: 4.6,
        description: "Relax in style with this modern recliner chair. Upholstered with soft fabric, it offers ergonomic support, making it perfect for reading, watching TV, or lounging.",
    },
    {
        title: "Wooden Coffee Table with Storage Space",
        name: "Coffee Table",
        imgURL: "https://images.pexels.com/photos/2903836/pexels-photo-2903836.jpeg",
        previousPrice: 150.00,
        salePrice: 129.99,
        category: "Furniture",
        rating: 4.5,
        description: "This elegant wooden coffee table provides ample storage space and complements any living room décor. Its sturdy construction and modern design make it both functional and stylish.",
    },
    {
        title: "Ultimate Guide to Personal Finance",
        name: "Personal Finance Book",
        imgURL: "https://images.pexels.com/photos/315655/pexels-photo-315655.jpeg",
        previousPrice: 20.00,
        salePrice: 14.99,
        category: "Books",
        rating: 4.8,
        description: "This comprehensive guide to personal finance covers budgeting, investing, and saving. A must-read for anyone looking to gain control of their financial future.",
    },
    {
        title: "Cooking for Beginners: A Step-by-Step Guide",
        name: "Cooking Book",
        imgURL: "https://images.pexels.com/photos/2559641/pexels-photo-2559641.jpeg",
        previousPrice: 25.00,
        salePrice: 18.99,
        category: "Books",
        rating: 4.7,
        description: "This beginner-friendly cookbook features easy-to-follow recipes and tips for those new to cooking. It includes everything from breakfast ideas to delicious dinners.",
    }
];

export default products;