const products = [
    {
        id: 1,
        title: "Stylish and Versatile Men's Casual Shirt for Everyday Comfort",
        name: "Shirt",
        imgURL: "https://images.pexels.com/photos/731909/pexels-photo-731909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 50.99,
        salePrice: 35.99,
        category: "Clothing",
        rating: 4.5,
        description: "This casual shirt is crafted from premium cotton fabric, making it breathable and lightweight. Designed for versatility, it can be worn for casual outings or semi-formal events. With a modern fit and durable stitching, it ensures long-lasting comfort and style. Pair it with jeans or chinos for a complete look.",
    },
    {
        id: 2,
        title: "Elegant and Spacious Women's Handbag for All Occasions",
        name: "Bag",
        imgURL: "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 60.99,
        salePrice: 45.99,
        category: "Accessories",
        rating: 4.8,
        description: "This elegant handbag is a must-have accessory for every modern woman. Made from high-quality faux leather, it combines durability with style. It features multiple compartments to keep your essentials organized, including space for your phone, wallet, and makeup. Perfect for daily use or special occasions, this handbag complements any outfit effortlessly.",
    },
    {
        id: 3,
        title: "Premium Noise-Canceling Wireless Headphones for Immersive Sound",
        name: "Headphones",
        imgURL: "https://images.pexels.com/photos/3394658/pexels-photo-3394658.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 120.99,
        salePrice: 89.99,
        category: "Electronics",
        rating: 4.6,
        description: "Experience superior sound quality with these wireless headphones. Equipped with advanced noise-canceling technology, they block out background noise, ensuring an immersive listening experience. The ergonomic design ensures a comfortable fit, even during extended use. With a long battery life and quick-charging feature, these headphones are perfect for music lovers and professionals alike.",
    },
    {
        id: 4,
        title: "Comfortable and Durable Running Shoes for Fitness Enthusiasts",
        name: "Shoes",
        imgURL: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 80.99,
        salePrice: 59.99,
        category: "Footwear",
        rating: 4.7,
        description: "Step up your fitness game with these lightweight and durable running shoes. Engineered for optimal performance, they feature a breathable mesh upper that keeps your feet cool and dry. The cushioned sole provides excellent shock absorption, reducing stress on your joints during workouts. Suitable for both beginners and seasoned runners.",
    },
    {
        id: 5,
        title: "Advanced Smartwatch with Health Monitoring and Customizable Design",
        name: "Watch",
        imgURL: "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        previousPrice: 150.99,
        salePrice: 129.99,
        category: "Electronics",
        rating: 4.9,
        description: "Stay connected and track your fitness goals with this stylish smartwatch. Featuring a sleek design and customizable watch faces, it seamlessly blends technology with fashion. The smartwatch includes health monitoring features such as heart rate tracking, sleep analysis, and step counting. With its water-resistant build and long battery life, it's perfect for active lifestyles.",
    },
    {
        id: 6,
        title: "Ultra-Soft Plush Throw Blanket for Ultimate Comfort",
        name: "Blanket",
        imgURL: "https://images.pexels.com/photos/1028698/pexels-photo-1028698.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 40.99,
        salePrice: 29.99,
        category: "Home & Living",
        rating: 4.7,
        description: "Stay cozy and warm with this ultra-soft plush throw blanket. Perfect for snuggling on the couch or adding a touch of elegance to your bedroom. It is made from premium microfiber material, ensuring durability and softness.",
    },
    {
        id: 7,
        title: "Set of Eco-Friendly Bamboo Cooking Utensils",
        name: "Cooking Utensils",
        imgURL: "https://images.pexels.com/photos/590822/pexels-photo-590822.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 25.99,
        salePrice: 19.99,
        category: "Kitchen",
        rating: 4.8,
        description: "Upgrade your kitchen with this eco-friendly set of bamboo cooking utensils. They are heat-resistant, lightweight, and safe for use with non-stick cookware. Perfect for cooking enthusiasts!",
    },
    {
        id: 8,
        title: "Portable Stainless Steel Insulated Water Bottle",
        name: "Water Bottle",
        imgURL: "https://images.pexels.com/photos/5867571/pexels-photo-5867571.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 20.99,
        salePrice: 14.99,
        category: "Accessories",
        rating: 4.6,
        description: "Stay hydrated throughout the day with this portable insulated water bottle. It keeps drinks cold for up to 24 hours and hot for up to 12 hours, making it perfect for outdoor adventures or daily use.",
    },
    {
        id: 9,
        title: "Ergonomic Office Chair for Enhanced Comfort and Support",
        name: "Office Chair",
        imgURL: "https://images.pexels.com/photos/691201/pexels-photo-691201.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 250.99,
        salePrice: 199.99,
        category: "Furniture",
        rating: 4.7,
        description: "Work comfortably for hours with this ergonomic office chair. It features adjustable height, lumbar support, and breathable mesh material for enhanced comfort and durability.",
    },
    {
        id: 10,
        title: "Rechargeable LED Desk Lamp with Touch Control",
        name: "Desk Lamp",
        imgURL: "https://images.pexels.com/photos/5728000/pexels-photo-5728000.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 40.99,
        salePrice: 29.99,
        category: "Electronics",
        rating: 4.8,
        description: "Illuminate your workspace with this sleek LED desk lamp. It features adjustable brightness levels, a touch control panel, and a rechargeable battery for convenience.",
    },
    {
        id: 11,
        title: "Stylish and Durable Leather Wallet for Men",
        name: "Wallet",
        imgURL: "https://images.pexels.com/photos/1267487/pexels-photo-1267487.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 30.99,
        salePrice: 24.99,
        category: "Accessories",
        rating: 4.9,
        description: "Carry your essentials in style with this genuine leather wallet. It features multiple compartments for cards and cash, making it both stylish and practical.",
    },
    {
        id: 12,
        title: "Non-Stick Ceramic Cookware Set for Healthy Cooking",
        name: "Cookware Set",
        imgURL: "https://images.pexels.com/photos/3965516/pexels-photo-3965516.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 120.99,
        salePrice: 99.99,
        category: "Kitchen",
        rating: 4.8,
        description: "Upgrade your cooking experience with this non-stick ceramic cookware set. Designed for even heat distribution, it makes healthy cooking effortless and cleaning a breeze.",
    },
    {
        id: 13,
        title: "Multi-Purpose Foldable Laptop Table for Home or Office",
        name: "Laptop Table",
        imgURL: "https://images.pexels.com/photos/4760833/pexels-photo-4760833.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 50.99,
        salePrice: 39.99,
        category: "Furniture",
        rating: 4.7,
        description: "Work or study comfortably with this foldable laptop table. It’s lightweight, adjustable, and portable, making it perfect for home or office use.",
    },
    {
        id: 14,
        title: "Deluxe Memory Foam Mattress Topper for Restful Sleep",
        name: "Mattress Topper",
        imgURL: "https://images.pexels.com/photos/416831/pexels-photo-416831.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 100.99,
        salePrice: 79.99,
        category: "Home & Living",
        rating: 4.8,
        description: "Improve your sleep quality with this deluxe memory foam mattress topper. It provides excellent support and comfort, ensuring a restful night’s sleep.",
    },
    {
        id: 15,
        title: "Colorful Yoga Mat with Non-Slip Surface",
        name: "Yoga Mat",
        imgURL: "https://images.pexels.com/photos/3823068/pexels-photo-3823068.jpeg?auto=compress&cs=tinysrgb&w=600",
        previousPrice: 30.99,
        salePrice: 22.99,
        category: "Fitness",
        rating: 4.9,
        description: "Enhance your workout routine with this colorful yoga mat. It features a non-slip surface and durable material, making it ideal for yoga, pilates, or any exercise.",
    },
];
